name: Build Keycloak ARM Docker Image 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get keycloak version
        id: get_tag
        run: |
          echo "DOCKER_TAG=$(echo "$(grep FROM Dockerfile)" | awk -F : '{print $2}')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/keycloak-arm:${{ steps.get_tag.outputs.DOCKER_TAG }}


